- hosts: all
    
  tasks:
  - name: SUDO CD 
    shell: 'pwd'
    become: true
    register: out
  
  - debug:
    msg: "{{ item }}"
    with_items: 
      - "{{ out.stderr_lines }}"
      - "{{ out.stdout_lines }}"

  



      
