---
- hosts: checkboxio

  roles:
    - deploy_checkboxio

  tasks:
      - name: Copying Auto_Test_Files
        copy: 
          src: /home/vagrant/DevOps-Project/checkbox_test_generation/
          dest: ~/
          remote_src: yes
          directory_mode: yes


      - name: Installing node modules inside it
        shell: 'npm install'
        sudo: true


#ansible-playbook -i "localhost," -c local provision_ec2.yml --extra-vars="param=checkboxio" --vault-password-file ~/.vault_pass.txt