---
- hosts: checkboxio

  roles:
    - deploy_checkboxio

  tasks:
      - name: Copying Auto_Test_Files
        copy: 
          src: ~/checkbox_test_generation/
          dest: ~/
          remote_src: yes
          directory_mode: yes


      - name: Installing node modules inside it
        shell: 'npm install'


#ansible-playbook -i "localhost," -c local provision_ec2.yml --extra-vars="param=checkboxio"