---
- hosts: jenkins
  
  vars_prompt:
    - name: "mysql_root_pass"
      prompt: "enter mysql root pass" 

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true

  roles:
    - java8
    - jenkins
    - ansible

  tasks:
    
    - name: copy roles to jenkins
      copy: 
        src: ~/roles
	dest: ~/roles
	owner: ubuntu
	group: ubuntu
	mode: 0666

    - name: copy files necessary to run checkbox 
      copy:
        src: ~/deploy_app_checkboxio.yml
	dest: ~/deploy_app_checkboxio.yml
	owner: ubuntu
	group: ubuntu
	mode: 0666

    - name: copy files necessary to run itrust
      copy:
        src: ~/deploy_app_iTrust2.yml
	dest: ~/deploy_app_iTrust2.yml
	owner: ubuntu
	group: ubuntu
	mode: 0666

    - name: copying additional necessary files
      copy:
        src: ~/provision_ec2.yml
	dest: ~/provision_ec2.yml
	owner: ubuntu
	group: ubuntu
	mode: 0666





