---
- hosts: jenkins
<<<<<<< HEAD
=======
  become: true
  vars:
    jenkins_path: /var/lib/jenkins
    jenkins_username: "admin"
    jenkins_password: "admin"
    jenkins_url: http://localhost:8080
    jenkins_params:
      url_username: "admin"
      url: "{{jenkins_url}}"
      validate_certs: no
    packages:
      - npm
      - debconf-utils
      - git
      - gcc
      - make
      - python-dev
      - python-pip
      - python-setuptools
      - python-lxml
      - vim
      - libffi-dev
      - libssl-dev
      - libxml2-dev 
      - libxslt1-dev 
      - libjpeg8-dev 
      - zlib1g-dev
    mysql_password: "{{ mysql_root_pass }}"
    
  vars_prompt:
    - name: "mysql_root_pass"
      prompt: "enter mysql root pass"
 

  roles:
    - java8
>>>>>>> 061ec1b139ecf9d16fb9ded4f6751a8bcf9f9a38
  
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true

<<<<<<< HEAD
  vars_prompt:
    - name: "mysql_root_pass"
      prompt: "enter mysql root pass"
=======
    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
      become: true

    - name: install mysql server
      apt:
        pkg: "{{ item }}"
        state: installed
      with_items:
        - mysql-server
      register: last_result
      become: yes
     
    - name: install client and libs
      apt:
        pkg: "{{ item }}"
        state: installed
      with_items:
        - mysql-client
        - python-mysqldb
        - php5-mysql
      become: yes

    - name: insert skip grant tables in my.cnf
      lineinfile: 
        dest: /etc/mysql/my.cnf
        insertafter: 'skip-external-locking'
        line: 'skip-grant-tables'
      become: true

    - name: restarting mysql
      service:
        name: mysql
        enabled: yes
        state: restarted
  
    - name: Installing Jenkins
      apt:
        name: jenkins     
        state: present
        update_cache: yes
      register: jenkins_install
      become: true

    - name: Restarting Jenkins
      service:
        name: jenkins
        state: restarted
      become: true

    - name: Wait while re-starting Jenkins
      wait_for: 
        port: 8080 
        delay: 20
    
    - name: Create Directory For Groovy Script - Jenkins
      file:
        path: "{{jenkins_path}}/init.groovy.d"
        state: directory
        mode: 0755
      register: groovy_dir
      become: true

    - name: Copying Groovy Script For Deafult Jenkins User(ADMIN) Creation
      template:
        force: yes
        src: "/home/vagrant/templates/jenkins_user.groovy.j2"
        dest: "{{jenkins_path}}/init.groovy.d/basic-security.groovy"
        mode: 0755
      become: true

    - name: Restarting Jenkins
      service:
        name: jenkins
        state: restarted
      become: true
>>>>>>> 061ec1b139ecf9d16fb9ded4f6751a8bcf9f9a38


  roles:
    - java8
    - jenkins

<<<<<<< HEAD
=======
    
>>>>>>> 061ec1b139ecf9d16fb9ded4f6751a8bcf9f9a38
