---
- name: enabling access to mvn without password 
  lineinfile:
    path: /etc/sudoers
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  become: true

- name: copy jenkins_jobs.ini file to jenkins server
  template:
    src: /home/vagrant/jenkins_jobs.ini
    dest: /home/vagrant/jenkins_jobs.ini
  become: true

- name: create jobs folder if it doesn't exit
  file:
    path: "/home/vagrant/jobs"
    state: directory

- name: Copy jenkins job builder script
  template:
    src: /home/vagrant/itrust_jenkins_jobs.yml
    dest: /home/vagrant/jobs/itrust_jenkins_jobs.yml
  # become: true

- name: Copy checkbox job builder script
  template:
    src: /home/vagrant/checkbox_jenkins_jobs.yml
    dest: /home/vagrant/jobs/checkbox_jenkins_jobs.yml
  # become: true


