- job:
    name: "{{itrust_deploy_job_name}}"
    scm:
      - git:
          url: git@github.ncsu.edu:khchoksi/iTrust2-v2.git
          branches:
            - origin/rolling_updates
          wipe-workspace: false
    triggers:
      - github:
    builders:
      - ansible-playbook:
            playbook: "/var/lib/jenkins/setup_itrust.yml"
            inventory-type: "path"
            inventory:
              path: "~/local_inventory"
            additional-parameters: '--vault-password-file ~/.vault_pass.txt --extra-vars "itrust_job_name={{itrust_deploy_job_name}}"'
      - shell: 'sleep 20s && cd /var/lib/jenkins/workspace/{{itrust_deploy_job_name}}/iTrust2/ && sudo mvn -f pom-data.xml process-test-classes'
      - shell: 'cd /var/lib/jenkins/workspace/{{itrust_deploy_job_name}}/iTrust2/ && sudo mvn clean test verify checkstyle:checkstyle'

    publishers:
     - postbuildscript:
         builders:
             - role: BOTH
               build-on:
                   - SUCCESS
               build-steps:
                   - shell: 'echo iTrust rolling deployment'
                   - shell: 'sudo ansible-playbook -i "localhost," -c local ~/provision_ec2_rolling_itrust.yml -e "ansible_python_interpreter=/usr/bin/python3"  && sudo ansible-playbook -i ~/inventory ~/deploy_app_iTrust2.yml -s --vault-password-file ~/.vault_pass.txt --extra-vars "var_host=deploy_itrust" -vvv'


