- scm: 
    name: GITHUB SCM
    scm:
      - git:
        url: git@github.ncsu.edu:khchoksi/iTrust2-v2.git
        branches:
          - */fuzzer
- job:
    name: "{{itrust_fuzzer_job_name}}"
    builders:
      - shell: 'sudo cp /var/lib/jenkins/workspace/{{itrust_fuzzer_job_name}}/iTrust2/src/main/resources/hibernate.properties.template /var/lib/jenkins/workspace/{{itrust_fuzzer_job_name}}/iTrust2/src/main/resources/hibernate.properties'
      - shell: 'sudo cp /var/lib/jenkins/workspace/{{itrust_fuzzer_job_name}}/iTrust2/src/main/java/db.properties.template /var/lib/jenkins/workspace/{{itrust_fuzzer_job_name}}/iTrust2/src/main/java/db.properties'
      - shell: 'sudo cp /home/ubuntu/email.properties /var/lib/jenkins/workspace/{{itrust_fuzzer_job_name}}/iTrust2/src/main/java/email.properties'
      - shell: 'sudo cp /home/ubuntu/pom-data.xml /var/lib/jenkins/workspace/{{itrust_fuzzer_job_name}}/iTrust2/pom-data.xml'
      - shell: 'cd /var/lib/jenkins/workspace/{{itrust_fuzzer_job_name}}/iTrust2/ && sudo mvn -f pom-data.xml process-test-classes'
      - shell: 'cd /var/lib/jenkins/workspace/{{itrust_fuzzer_job_name}}/iTrust2/ && sudo mvn clean test verify checkstyle:checkstyle'

    # publishers:
    #   - jacoco:
    #       exec-pattern: '**/**.exec'
    #       #class-pattern: '**/EmailUtil.class'
    #       class-pattern: '**/classes'
    #       source-pattern: '**/src'
    #       update-build-status: true
    #       exclusion-pattern: '**/*Test*.class'
#      - postbuildscript:
 #         builders:
  #           - build-steps:
   #            - shell: 'cd && sudo ansible-playbook -i "localhost," -c local ~/provision_ec2.yml --extra-vars="param=iTrust2" && sleep 69s && sudo chmod 400 ~/keys/iTrust2.pem && sudo ansible-playbook -i ~/inventory ~/deploy_app_iTrust2.yml -s --vault-password-file ~/.vault_pass.txt '



      # - ansible-playbook:
      #     playbook: "/home/ubuntu/itrust_fuzzer_builder.yml"
      #     inventory-type: "path"
      #     inventory:
      #       path: "/home/ubuntu/local_inventory" 
      #     additional-parameters: "-vvv"

#java -jar jenkins-cli.jar -s http://localhost:8080/ build itrust_job --username {{ jenkins_username }} --password {{ jenkins_password }}


