---
- hosts: jenkins
  vars:
  - jenkins_ip: "localhost"  
  - jenkins_port: 8080
  - jenkins_username: "admin"
  - jenkins_password: "admin"
  - job_name: "checkbox_job01"

      
  # vars_prompt:
  # - name: Enter Jenkins Password
  #   prompt: "Enter Jenkins Password for admin"
 
  tasks:
  # - name: enabling access to mvn without password 
  #   lineinfile:
  #     path: /etc/sudoers
  #     line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  #   become: true

  # - name: copy jenkins_jobs.ini file to jenkins server
  #   template:
  #     src: /home/vagrant/jenkins_jobs.ini
  #     dest: /home/vagrant/jenkins_jobs.ini
  #   become: true

  # - name: create jobs folder if it doesn't exit
  #   file:
  #     path: "/home/vagrant/jobs"
  #     state: directory

  - name: Copy jenkins job builder script
    template:
      src: /home/vagrant/checkbox_jenkins_jobs.yml
      dest: /home/vagrant/jobs/checkbox_job_builder.yml
    # become: true

  - name: create jobs
    shell: 'jenkins-jobs --conf /home/vagrant/jenkins_jobs.ini update /home/vagrant/jobs/checkbox_job_builder.yml'
    become: true

  - name: change directories
    shell: 'cd /home/vagrant/'
    become: true

  - name: check itrust git folder if it exists
    stat:
      path: "/var/lib/jenkins/workspace/{{job_name}}/checkbox.io/"
    register: itrust_git_file

  - name: delete if the directory exists
    file:
      state: absent
      path: "/var/lib/jenkins/workspace/{{job_name}}/checkbox.io/"
    when: itrust_git_file.stat.exists
    become: true

  - name: build jobs
    shell: 'java -jar jenkins-cli.jar -s http://localhost:8080/ build {{job_name}} --username {{ jenkins_username }} --password {{ jenkins_password }}'
    become: true





