---
- hosts: jenkins
  become: true
  vars:
    jenkins_path: /var/lib/jenkins
    jenkins_username: "admin"
    jenkins_password: "admin"
    jenkins_url: http://localhost:8080
    jenkins_params:
      url_username: "admin"
      url: "{{jenkins_url}}"
      validate_certs: no
    packages:
      - npm
      - debconf-utils
      - git
      - gcc
      - make
      - python-dev
      - python-pip
      - python-setuptools
      - python-lxml
      - vim
      - libffi-dev
      - libssl-dev
      - libxml2-dev 
      - libxslt1-dev 
      - libjpeg8-dev 
      - zlib1g-dev

  roles:
    - java8
  
  tasks:
    - name: Install Maven
      apt: pkg=maven state=present
      become: true

    - name: Adding Apt Key For Jenkins
      apt_key:
        url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
        state: present
        validate_certs: no
      become: true

    - name: Check For Jenkins List    
      stat: path=/etc/apt/sources.list.d/jenkins.list
      register: jenkins_list

    - name: Adding Jenkins Source List
      shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
      when: not jenkins_list.stat.exists
      become: true
    
    - name: Installing Jenkins
      apt:
        name: jenkins     
        state: present
        update_cache: yes
      register: jenkins_install
      become: true

    - name: Restarting Jenkins
      service:
        name: jenkins
        state: restarted
      become: true

    - name: Wait while re-starting Jenkins
      wait_for: 
        port: 8080 
        delay: 20
    
    - name: Create Directory For Groovy Script - Jenkins
      file:
        path: "{{jenkins_path}}/init.groovy.d"
        state: directory
        mode: 0755
      register: groovy_dir
      become: true

    - name: Copying Groovy Script For Deafult Jenkins User(ADMIN) Creation
      template:
        force: yes
        src: "/home/vagrant/templates/jenkins_user.groovy.j2"
        dest: "{{jenkins_path}}/init.groovy.d/basic-security.groovy"
        mode: 0755
      become: true

    - name: Restarting Jenkins
      service:
        name: jenkins
        state: restarted
      become: true

    - name: Wait while re-starting Jenkins
      wait_for: 
        port: 8080 
        delay: 30

    - name: Removing Groovy Script so it doesn't create furthermore user
      file:
        path: "{{jenkins_path}}/init.groovy.d/basic-security.groovy"
        state: absent
      become: true

    - name: Getting Jenkins CLI Jar
      get_url:
        url: "{{jenkins_url}}/jnlpJars/jenkins-cli.jar"
        dest: "/home/vagrant/"
        mode: 0755
      become: true
      when: groovy_dir.changed

    - name: Wait while re-starting Jenkins
      wait_for: 
        port: 8080 
        delay: 30

    - name: Install packages for node machine
      apt: pkg="{{item}}" state=present update_cache=true
      with_items: 
        - npm
        - maven
        - python-dev
        - python-pip
        - python-setuptools
        - python-lxml
        - vim
        - git
        - html-xml-utils
        - jetty
      become: true

    - pip:
        name: jenkins-job-builder

    - name: Install Jenkin Plugins
      jenkins_plugin:
        name: "{{ item }}"
        params: "{{ jenkins_params }}"
        url_password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
      with_items:
        - github
        - maven-plugin
        - jacoco
        - junit
        - test-stability
        - postbuildscript
        - build-timeout
        - postbuild-task
        - ws-cleanup
        - jenkins-job-builder
        - html-xml-utils
        

    - name: Restarting Jenkins
      service:
        name: jenkins
        state: restarted
      become: true

    - name: Checking Jenkins State
      service:
        name: jenkins
        state: started
      become: true

    