apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-claim0
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-claim1
        - mountPath: /etc/nginx/sites-available/default
          name: nginx-claim2
      restartPolicy: Always
      volumes:
      - name: nginx-claim0
        hostPath:
          path: /home/centos/checkbox.io/public_html
          type: Directory
      - name: nginx-claim1
        hostPath:
          path: /home/centos/checkbox.io/local-conf/nginx.conf
          type: File
      - name: nginx-claim2
        hostPath:
          path: /home/centos/checkbox.io/local-conf/default
          type: File
status: {}