---
- name: Copy prioritization.js to EC2 
  copy:
    src: ~/DevOps-Project/roles/prioritization/templates/prioritization.js
    dest: /home/ubuntu/prioritization.js
    owner: ubuntu
    group: ubuntu
    mode: 0777
  become: true

- name: Copy package.json for prioritization.js
  copy:
    src: ~/DevOps-Project/roles/prioritization/templates/package.json
    dest: /home/ubuntu/package.json
    owner: ubuntu
    group: ubuntu
    mode: 0777
  become: true

# Delete the previous report if it exists
- name: "DELETE previous prioritization report if it exists"
  file:
    path: /home/ubuntu/Prioritization_Report.txt
    state: absent

- name: "Install node dependencies for prioritization.js"
  shell: 'sudo npm install && node prioritization.js'
  become: true

- name: Wait until the report is generated
  wait_for:
    path: /home/ubuntu/Prioritization_Report.txt
    state: present
  become: true

#Copy report from EC2 instance to host machine
- name: Fetch Report from the EC2 instance to host machine
  fetch: 
    src: /home/ubuntu/Prioritization_Report.txt
    dest: /home/vagrant/
    flat: yes
  become: true

- name: Remove all previous test results 
  file:
    state: absent
    path: /home/ubuntu/test_reports/
  become: true


