---
- name: Install dependencies
  shell: 'npm install'
  args:
    chdir: "./roles/ec2_for_checkboxio/templates"

- name: Create EC2 instance
  shell: 'node ec2_createinstances.js {{param}}' 
  args:
    chdir: "./roles/ec2_for_checkboxio/templates"

