---
- hosts: localhost

  tasks:

     - name: Fetch AWS Credential File Content
       set_fact:
          content: "{{item}}"
       no_log: true
       with_file:
          - "/var/lib/jenkins/.aws/credentials"
       become: true

     - name: Set AWS Access Key Variable
       set_fact:
          aws_access_key: "{{ content.split('=')[1] | replace('\naws_secret_access_key', '') | trim }}"

     - name: Set AWS Secret Key Variable
       set_fact:
          aws_secret_key: "{{ content.split('=')[2] | trim }}"

     - name: "Checking Deploy_iTrust EC2 Instance Exists"
       ec2_instance_facts:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          region: "us-west-2"
          filters:
              "tag:Name": deploy_itrust
              "instance-state-code": "16"
       register: ec2_deploy_itrust


     - name: Create EC2 instance for deploy_itrust deployment
       shell: 'sudo ansible-playbook -i "localhost," -c local ~/provision_ec2_itrust.yml --extra-vars="param=deploy_itrust" -e "ansible_python_interpreter=/usr/bin/python3"  && sleep 30s && sudo chmod 400 /var/lib/jenkins/keys/deploy_itrust.pem'
       become: true
       when: ec2_deploy_itrust.instances | length==0

     - name: "Get Public IP for deploy_itrust instance"
       set_fact:
          ec2_ip: "ec2_deploy_itrust.instances[0].public_ip_address"
       when: ec2_deploy_itrust.instances | length>0

     - name: Waiting for EC2 instance to spinup
       shell: "sleep 30s"
       when: ec2_deploy_itrust.instances | length==0
