---
- hosts: localhost

  tasks:

     - name: Fetch AWS Credential File Content
       set_fact:
          content: "{{item}}"
       no_log: true
       with_file:
          - "/var/lib/jenkins/.aws/credentials"
       become: true

     - name: Set AWS Access Key Variable
       set_fact:
          aws_access_key: "{{ content.split('=')[1] | replace('\naws_secret_access_key', '') | trim }}"

     - name: Set AWS Secret Key Variable
       set_fact:
          aws_secret_key: "{{ content.split('=')[2] | trim }}"

     - name: Fetching EC2 instance details of Jenkins
       ec2_instance_facts:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          region: "us-west-2"
          filters:
             "tag:Name": jenkins
             "instance-state-code": "16"
       register: ec2_jenkins

     - name: Get Public IP for Jenkins EC2  instance
       set_fact:
          ec2_jenkins_ip: "{{ec2_jenkins.instances[0].public_ip_address}}"
       when: ec2_jenkins.instances | length>0

     - name: "Checking first Checkbox EC2 Instance Exist or not"
       ec2_instance_facts:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          region: "us-west-2"
          filters:
              "tag:Name": canary-checkboxio
              "instance-state-code": "16"
       register: ec2_deploy_canary_checboxio

     - name: Create EC2 instance for canary release of Checkbox.io
       shell: 'sudo ansible-playbook -i "localhost," -c local ~/create_ec2_checkbox.yml --extra-vars="param=canary-checkboxio" -e "ansible_python_interpreter=/usr/bin/python3" '
       become: true
       when: ec2_deploy_canary_checboxio.instances | length==0

     - name: "Get Public IP for checkbox canary instance"
       set_fact:
          ec2_ip: "ec2_deploy_canary_checboxio.instances[0].public_ip_address"
       when: ec2_deploy_canary_checboxio.instances | length>0

     - name: Waiting for EC2 instance to spinup
       shell: "sleep 30s"
       when: ec2_deploy_canary_checboxio.instances | length==0



