---
- name: enabling access to mvn without password 
  lineinfile:
    path: /etc/sudoers
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  become: true

#- name: copy jenkins_jobs.ini file to jenkins server
#  template:
#    src: ~/roles/create_jobs/templates/jenkins_jobs.ini
#    dest: /home/vagrant/jenkins_jobs.ini
#  become: true

#- name: create jobs folder if it doesn't exit
#  file:
#    path: "/home/ubuntu/jobs"
#    state: directory

- name: Create .ssh folder if it doesn't exit
  file:
    path: "/var/lib/jenkins/.ssh"
    state: directory
  become: true

- name: Copy private SSH Key for GitHub to var lib jenkins
  copy:
    src: ~/.ssh/git_rsa
    dest: /var/lib/jenkins/.ssh/id_rsa
    owner: jenkins
    group: jenkins
    mode: 0400
  become: true

- name: Copy pom-data.xml for iTrustv2
  copy:
    src: "{{ project_directory }}/roles/create_jobs/templates/pom-data.xml"
    dest: /var/lib/jenkins/pom-data.xml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

- name: Copy localinventory for localhost of Jenkins EC2
  copy:
    src: "{{ project_directory }}/roles/create_jobs/templates/local_inventory"
    dest: /var/lib/jenkins/local_inventory
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

#Job Builder Playbook for iTrust Test
- name: Copy builder playbook for iTrust
  copy:
    src: "{{ project_directory }}/roles/create_jobs/templates/builder_itrust.yml"
    dest: /var/lib/jenkins/builder_itrust.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

#Job Builder Playbook for iTrust Fuzzing
- name: Copy builder playbook for iTrust Fuzzer
  copy:
    src: "{{ project_directory }}/roles/create_jobs/templates/builder_itrust_fuzzer.yml"
    dest: /var/lib/jenkins/builder_itrust_fuzzer.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true


- name: Copy iTrust jenkins job  script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/itrust_jenkins_jobs.yml"
    dest: ~/jobs/itrust_jenkins_jobs.yml
  # become: true

- name: Copy checkbox job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/checkbox_jenkins_jobs.yml"
    dest: ~/jobs/checkbox_jenkins_jobs.yml
  # become: true

- name: Copy iTrust Fuzzer jenkins job  script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/itrust_fuzzing.yml"
    dest: ~/jobs/itrust_fuzzing.yml

# Checkbox.io job for deployment which will run after every push to repo
- name: Copy Checkbox.io Deployment jenkins job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/deploy_checkbox_jenkins_job.yml"
    dest: ~/jobs/deploy_checkbox_jenkins_job.yml

# iTrustv2 job for deployment which will run after every push to repo
- name: Copy iTrustv2 Deployment jenkins job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/deploy_itrust_jenkins_job.yml"
    dest: ~/jobs/deploy_itrust_jenkins_job.yml
  
- name: create jobs
  shell: 'cd  && jenkins-jobs --conf ~/jenkins_jobs.ini update ~/jobs'
  #become: true

# New
- name: Creating new directory for test_reports
  file:
    path: /home/ubuntu/test_reports
    state: directory
    mode: 0766
