---
- name: enabling access to mvn without password 
  lineinfile:
    path: /etc/sudoers
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  become: true

#- name: copy jenkins_jobs.ini file to jenkins server
#  template:
#    src: ~/roles/create_jobs/templates/jenkins_jobs.ini
#    dest: /home/vagrant/jenkins_jobs.ini
#  become: true

#- name: create jobs folder if it doesn't exit
#  file:
#    path: "/home/ubuntu/jobs"
#    state: directory

- name: Create .ssh folder if it doesn't exit
  file:
    path: "/var/lib/jenkins/.ssh"
    state: directory
    owner: jenkins
    group: jenkins
  become: true

- name: Copy private SSH Key for GitHub to var lib jenkins
  copy:
    src: ~/.ssh/git_rsa
    dest: /var/lib/jenkins/.ssh/id_rsa
    owner: jenkins
    group: jenkins
    mode: 0400
  become: true

- name: Copy pom-data.xml for iTrustv2
  copy:
    src: "{{ project_directory }}/roles/create_jobs/templates/pom-data.xml"
    dest: /var/lib/jenkins/pom-data.xml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

- name: Copy localinventory for localhost of Jenkins EC2
  copy:
    src: "{{ project_directory }}/roles/create_jobs/templates/local_inventory"
    dest: /var/lib/jenkins/local_inventory
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

#Playbook to create EC2 instance for DEPLOY_CHECKBOXIO
- name: Copy playbook for creating ec2 instance for deploy_checkboxio
  copy:
    src: "{{ project_directory }}/roles/create_jobs/files/provision_ec2_checkboxio.yml"
    dest: /var/lib/jenkins/provision_ec2_checkboxio.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

#Playbook to create EC2 instance for DEPLOY_ITRUST
- name: Copy playbook for creating ec2 instance for deploy_checkboxio
  copy:
    src: "{{ project_directory }}/roles/create_jobs/files/provision_ec2_itrust.yml"
    dest: /var/lib/jenkins/provision_ec2_itrust.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

#Playbook to create five EC2 instances for rolling DEPLOY_ITRUST
- name: Copy playbook for creating five ec2 instances for rolling itrust
  copy:
    src: "{{ project_directory }}/roles/create_jobs/files/provision_ec2_rolling_itrust.yml"
    dest: /var/lib/jenkins/provision_ec2_rolling_itrust.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

#Job Builder Playbook for iTrust Test
- name: Copy builder playbook for iTrust
  copy:
    src: "{{ project_directory }}/roles/create_jobs/templates/builder_itrust.yml"
    dest: /var/lib/jenkins/builder_itrust.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true

#Job Builder Playbook for iTrust Setup
- name: Copy builder playbook for iTrust Setup like properites and pom-data
  copy:
    src: "{{ project_directory }}/roles/create_jobs/templates/setup_itrust.yml"
    dest: /var/lib/jenkins/setup_itrust.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true


- name: Copy iTrust jenkins job  script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/itrust_jenkins_jobs.yml"
    dest: ~/jobs/itrust_jenkins_jobs.yml
  # become: true

- name: Copy checkbox job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/checkbox_jenkins_jobs.yml"
    dest: ~/jobs/checkbox_jenkins_jobs.yml
  # become: true

- name: Copy iTrust Fuzzer jenkins job  script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/itrust_fuzzing.yml"
    dest: ~/jobs/itrust_fuzzing.yml

# Checkbox.io job for deployment which will run after every push to repo
- name: Copy Checkbox.io Deployment jenkins job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/deploy_checkbox_jenkins_job.yml"
    dest: ~/jobs/deploy_checkbox_jenkins_job.yml

# iTrustv2 job for deployment which will run after every push to repo
- name: Copy iTrustv2 Deployment jenkins job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/deploy_itrust_jenkins_job.yml"
    dest: ~/jobs/deploy_itrust_jenkins_job.yml

# iTrustv2 rolling update job for deployment which will run after every push to repo
- name: Copy iTrustv2 rolling Deployment jenkins job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/itrust_rolling_jenkins_job.yml"
    dest: ~/jobs/itrust_rolling_jenkins_job.yml

#Ansible playbook to create iTrust instances in different ansible playbook
- name: Copy Ansible playbook to create iTrust instances in different ansible playbook
  copy:
    src: "{{ project_directory }}/roles/create_jobs/files/create_ec2_itrust.yml"
    dest: /var/lib/jenkins/create_ec2_itrust.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: true
  
- name: create jobs
  shell: 'cd  && jenkins-jobs --conf ~/jenkins_jobs.ini update ~/jobs'
  #become: true

#Following tasks are for first time deployment on checkbox io & iTrust on deployment environment 
- name: Initial Deployment of Checkbox.io
  shell: 'java -jar jenkins-cli.jar -s http://localhost:8090/ build {{ checkbox_deploy_job_name }} --username {{ jenkins_username }} --password {{ jenkins_password }}'

- name: Initial Deployment of iTrust2
  shell: 'sleep 60s & java -jar jenkins-cli.jar -s http://localhost:8090/ build {{ itrust_deploy_job_name }} --username {{ jenkins_username }} --password {{ jenkins_password }}'

# New
- name: Creating new directory for test_reports
  file:
    path: /home/ubuntu/test_reports
    state: directory
    mode: 0766
