---
- name: check if checkbox git folder exists
  stat:
    path: "/var/lib/jenkins/workspace/{{ checkbox_job_name }}/checkbox.io/"
  register: itrust_git_file

- name: delete if the checkbox git directory exists
  file:
    state: absent
    path: "/var/lib/jenkins/workspace/{{ checkbox_job_name }}/checkbox.io/"
  when: itrust_git_file.stat.exists
  become: true

- name: build checkbox job
  shell: 'java -jar jenkins-cli.jar -s http://localhost:8090/ build {{ checkbox_job_name }} --username {{ jenkins_username }} --password {{ jenkins_password }}'
  become: true

- name: check if itrust git folder exists
  stat:
    path: "/var/lib/jenkins/workspace/{{ itrust_job_name }}/iTrust2-v2/"
  register: itrust_git_file

- name: delete if the itrust directory exists
  file:
    state: absent
    path: "/var/lib/jenkins/workspace/{{ itrust_job_name }}/iTrust2-v2/"
  when: itrust_git_file.stat.exists
  become: true

- name: build itrust job
  shell: 'java -jar jenkins-cli.jar -s http://localhost:8090/ build {{ itrust_job_name }} --username {{ jenkins_username }} --password {{ jenkins_password }}'
  become: true


