---
- name: Add ansible repository from PPA
  become: yes
  apt_repository:
    repo: 'ppa:ansible/ansible'

- name: Install ansible
  become: yes
  apt:
    name: ansible
    state: latest
    update_cache: yes
    force: yes


