---
- name: enabling access to mvn without password 
  lineinfile:
    path: /etc/sudoers
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  become: true

#- name: copy jenkins_jobs.ini file to jenkins server
#  template:
#    src: ~/roles/create_jobs/templates/jenkins_jobs.ini
#    dest: /home/vagrant/jenkins_jobs.ini
#  become: true

#- name: create jobs folder if it doesn't exit
#  file:
#    path: "/home/ubuntu/jobs"
#    state: directory

- name: Copy jenkins job builder script
  template:
    src: ~/roles/create_jobs/templates/itrust_jenkins_jobs.yml
    dest: ~/jobs/itrust_jenkins_jobs.yml
  # become: true

- name: Copy checkbox job builder script
  template:
    src: ~/roles/create_jobs/templates/checkbox_jenkins_jobs.yml
    dest: ~/jobs/checkbox_jenkins_jobs.yml
  # become: true
  
- name: create jobs
  shell: 'cd && jenkins-jobs --conf ~/jenkins_jobs.ini update ~/jobs'
  #become: true
