---
#- name: Copy private SSH Key for GitHub
#  copy:
#    src: ~/.ssh/git_rsa
#    dest: /root/.ssh/git_rsa
#    mode: 0400
#  become: true

##- name: Add the identity file inconfiguration
 # shell: 'sudo su && cd /root/.ssh && eval "$(ssh-agent -s)" && ssh-add -k /root/.ssh/git_rsa'
 # become: true

#- name: GIT CLONE
#  shell: 'cd /home/vagrant/iTrustClone && git clone git@github.ncsu.edu:engr-csc326-staff/iTrust2-v2.git'
#  become: true
- name: DELETE iTrustClone dirctory if it exists
  file: 
    path: "{{itrust_directory}}"
    state: absent

- name: CREATE iTrustClone directory
  file: 
    path: "{{itrust_directory}}"
    state: directory
    mode: 0775

- name: Git Clone
  git:
    repo: 'git@github.ncsu.edu:khchoksi/iTrust2-v2.git'
    dest: "{{itrust_directory}}"

- name: Add Pre-Push Hook
  template:
    src: "{{ project_directory }}/roles/fuzzer/templates/pre-push-hook"
    dest: "{{itrust_directory}}/.git/hooks/pre-push"
    mode: 0767
  

- name: Add Fuzzer.js file
  copy:
    src: "{{ project_directory }}/roles/fuzzer/files/fuzzer.js"
    dest: "{{itrust_directory}}/fuzzer.js"
    mode: 0666

- name: adding package.json file for fuzzer.js
  copy: 
    src: "{{ project_directory}}/roles/fuzzer/files/package.json"
    dest: "{{itrust_directory}}/package.json"


- name: Git add and checkout to master
  shell: "cd {{itrust_directory}} && npm install && git checkout master && touch fuzzer.js && git add . && git commit -m \"Commiting to master by developer\" && git push"


