---
- name: Add an apt key by id from ubuntu keyserver
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 68576280

- name: Add repository for node 7
  shell: sudo apt-add-repository "deb https://deb.nodesource.com/node_7.x $(lsb_release -sc) main"
  become: yes

- name: Import MongoDB public GPG Key from ubuntu keyserver
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

- name: Add repository for MongoDB
  shell: sudo apt-add-repository "deb [ arch=$(dpkg --print-architecture) ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -sc)/mongodb-org/3.6 multiverse"
  become: yes


- name: Install latest package
  become: yes
  with_items:
    - nodejs
    - nginx
    - git
    - mongodb
    - python-pip
  apt:
    name: '{{item}}'
    state: latest
    update_cache: yes
    force: yes

- name: Install pymongo
  become: yes
  pip:
    name: pymongo
    state: latest

- name: Create a new database and user in MongoDB
  mongodb_user: 
    database: '{{database_name}}'
    name: '{{database_user}}'
    password: '{{database_password}}'
    roles: readWrite,dbAdmin,userAdmin

- name: Creates directory for checkbox
  file:
    path: "{{ lookup('env','HOME') }}/checkbox"
    state: directory
    mode: 0775
    recurse: yes

- name: Clone checkbox.io
  git:
    repo: 'https://github.com/chrisparnin/checkbox.io.git'
    dest: "{{ lookup('env','HOME') }}/checkbox"
    update: no

- name: Install forever package using npm
  become: yes
  npm:
    global: yes
    name: forever

- name: Install dependencies npm
  npm:
    path: "{{ lookup('env','HOME') }}/checkbox/server-side/site"

- name: Replace the server root in the "default" file
  replace:
    dest: "{{ lookup('env','HOME') }}/checkbox/local-conf/default"
    regexp: "root (.)+;"
    replace: "root {{ lookup('env','HOME') }}/checkbox/public_html/;"

- name: 'Copy files from checkbox to nginx available sites'
  become: yes
  copy:
    src: "{{ lookup('env','HOME') }}/checkbox/local-conf/default"
    dest: /etc/nginx/sites-available/default
    remote_src: yes
    mode: 0644

- name: 'Copy nginx conf file'
  become: yes
  copy:
    src: "{{ lookup('env','HOME') }}/checkbox/local-conf/nginx.conf"
    dest: /etc/nginx/nginx.conf
    remote_src: yes
    mode: 0644

- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted

- name: Starting/Restarting nginx using forever
  shell: forever stopall; forever start server.js
  args:
    chdir: "{{ lookup('env','HOME') }}/checkbox/server-side/site/"
  environment:
    MONGO_PORT: 3002
    MONGO_IP: 127.0.0.1
    MONGO_USER: '{{database_user}}'
    MONGO_PASSWORD: '{{database_password}}'
    MAIL_USER: devops519pkkn
    MAIL_PASSWORD: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38663863626436393036313831666134306165336535353663316663613364373634333135333038
          3730313736653133373736393438333439316538633166370a366566346235643966663035623436
          39396462643565346535636132616362303737636438623137336434646232333730373436373435
          3062653665616164310a663537626661376535656234666434663563386137333738396335633061
          3164
    MAIL_SMTP: 'smtp.gmail.com'
