apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: checkbox
    spec:
        containers:
        - name: checkbox
          image: kjpatel4/checkbox
          ports:
          - containerPort: 80
